### PR TITLE
Sunset BlockEQ 😔

### PR DESCRIPTION
**Pull request by lolpuddle**
## Priority
Normal

## Description
* Adds an alert to inform users BlockEQ is deprecated
* Updates to fix iOS 13 bugs

## Screenshot
Simulator Screen Shot - iPhone 11 - 2019-11-08 at 13 22 22

### CODE REVIEW

**Comment by dabitdev** [comment]
I did not put your `friends at StellarX`.
I do not see you deleting inflation feature, did you?

**Review by dluu2015 — APPROVED** [review]
+1

**Comment by lolpuddle** [comment]
> I did not put your `friends at StellarX`.
> I do not see you deleting inflation feature, did you?

Hid capabilities to set inflation, the `friends at StellarX` comes from the provided description in the ticket

**Comment by dabitdev** [comment]
did you enable tracking campaign?

**Pull request merged**
